# TODO: needs to be updated for ic
# services:
#   ultraviolet:
#     image: diffusehyperion/ultraviolet
#     container_name: campus
#     restart: unless-stopped
#     ports:
#       - "8080:8080"

# networks:
#   default:
#     name: ultraviolet
